# Generated by Django 6.1.1 on 2026-09-25 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.TextField()),
                ('legal_problem', models.TextField()),
                ('incident_description', models.TextField()),
                ('preferred_channel', models.CharField(choices=[('web', 'Web Portal'), ('udc', 'Union Digital Centre (UDC)'), ('helpline', '16699 Helpline'), ('walk_in', 'Office Walk-in')], default='web', max_length=32)),
                ('safe_contact_number', models.CharField(blank=True, max_length=32)),
                ('safe_contact_time', models.CharField(blank=True, max_length=128)),
                ('language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('REFERRED', 'Referred'), ('MEDIATION', 'Mediation'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='ACCEPTED', max_length=32)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case_record', to='cases.application')),
                ('assigned_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lawyer_cases', to=settings.AUTH_USER_MODEL)),
                ('assigned_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_officer_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Record',
                'verbose_name_plural': 'Case Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=64)),
                ('channel', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('provenance', models.CharField(choices=[('applicant_confirmed', 'Applicant-Confirmed'), ('representative_reported', 'Representative-Reported'), ('intermediary_translated', 'Intermediary-Translated'), ('staff_entered', 'Staff-Entered'), ('ai_inferred', 'AI-Inferred')], max_length=64)),
                ('authority', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cases.caserecord')),
            ],
            options={
                'verbose_name': 'Case Event',
                'verbose_name_plural': 'Case Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('voice', 'Voice'), ('sms', 'SMS'), ('web', 'Web'), ('udc', 'UDC'), ('walk_in', 'Walk-in')], max_length=32)),
                ('recipient', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('result', models.CharField(default='sent', max_length=64)),
                ('safe_contact_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_communications', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='cases.caserecord')),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('match_reason', models.TextField()),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed Duplicate'), ('dismissed', 'Dismissed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates', to='cases.caserecord')),
                ('possible_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_duplicate_candidates', to='cases.caserecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_duplicate_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duplicate Candidate',
                'verbose_name_plural': 'Duplicate Candidates',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.caserecord')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cases', to='cases.caserecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_relationships', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_related_cases', to='cases.caserecord')),
            ],
            options={
                'verbose_name': 'Related Case Link',
                'verbose_name_plural': 'Related Case Links',
                'unique_together': {('case', 'related_case')},
            },
        ),
    ]
