# Generated by Django 6.0.6 on 2026-09-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseevent_application_alter_caseevent_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='nid_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='nid_verification_status',
            field=models.CharField(choices=[('not_verified', 'Not verified'), ('verification_pending', 'Verification pending'), ('verified', 'Verified'), ('verification_failed', 'Verification failed')], default='not_verified', max_length=32),
        ),
    ]
