# Generated by Django 6.0.6 on 2026-09-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_application_nid_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='idempotency_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='application',
            name='original_statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='statement_language',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='translated_statement',
            field=models.TextField(blank=True, default=''),
        ),
    ]
