# Generated by Django 6.1.1 on 2026-09-25 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('in_person', 'In-Person'), ('hybrid', 'Hybrid'), ('remote', 'Remote / Online')], default='in_person', max_length=32)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(default='pending', max_length=64)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Scheduling'), ('scheduled', 'Scheduled'), ('in_progress', 'In Session'), ('agreed', 'Settlement Reached'), ('failed', 'Mediation Failed / Unresolved'), ('closed', 'Closed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mediation', to='cases.caserecord')),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mediation',
                'verbose_name_plural': 'Mediations',
                'ordering': ['-created_at'],
            },
        ),
    ]
