# Generated by Django 6.1.1 on 2026-09-25 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('representative', 'Representative'), ('helpline_agent', 'Helpline Agent'), ('dlao_officer', 'DLAO Officer'), ('dlao_support_staff', 'DLAO Support Staff'), ('udc_operator', 'UDC Operator'), ('panel_lawyer', 'Panel Lawyer'), ('mediator', 'Mediator'), ('admin', 'Admin')], default='citizen', max_length=32)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
