# Generated by Django 6.1.1 on 2026-09-25 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Acceptance'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('changed', 'Reassigned/Changed'), ('completed', 'Completed')], default='pending', max_length=32)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lawyer_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lawyer_assignments', to='cases.caserecord')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lawyer Assignment',
                'verbose_name_plural': 'Lawyer Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
